substitutions:
  device_name: testunit
  run_duration: 1min
  sleep_duration: 6hours
  minimum_raw_value: '3800'
  maximum_raw_value: '6800'
  temperature_offset: '-5'
  battery_update_interval: '30s'
  temperature_update_interval: '5s'
  moisture_update_interval: '5s'
  
<<: !include default-template.yaml
